---
apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: letsencrypt-prod
  namespace: pfc

spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kennycallado@gmail.com
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - selector: {}
      http01:
        ingress: {}
